# Generated by Django 3.0.6 on 2020-06-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20200623_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
