# Generated by Django 3.0.6 on 2020-06-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0004_auto_20200625_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polling.Question'),
        ),
    ]
