# Generated by Django 3.0.6 on 2020-06-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0006_auto_20200626_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
