# Generated by Django 3.0.6 on 2020-06-28 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polling', '0007_auto_20200627_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='choosers',
            field=models.ManyToManyField(null=True, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
