# Generated by Django 3.0.6 on 2020-06-28 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polling', '0008_auto_20200628_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='choosers',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
