# Generated by Django 3.0.6 on 2020-06-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0009_auto_20200628_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
